// badge-library.jsx — COMPOUND full 500-badge library (generated; do not hand-edit the array).
// Headline of Change Round 3, item 10. Replaces the legacy ~36-badge BADGES list in badges.jsx.
//
// Each badge: { id, n, cat, glyph, track, gate?, special?, name, cond }
//   n       — stable 1..500 ordinal (matches James's master list)
//   cat     — category key (see BADGE_LIB_CATEGORIES)
//   glyph   — key into the merged BADGE_GLYPHS dict (BL_NEW_GLYPHS adds the new ones)
//   track   — data source that PROVES the badge, so you know what to wire:
//             nips | checkins | food | workouts | measurements   → sources that EXIST today
//             sleep | mind | water | goals | social | app | manual | mixed → need NEW tracking;
//             define the store first, then write the evaluator. Until then the badge is DEFINED
//             but stays locked (shows in the wall greyed, "tracking coming soon").
//   gate    — 'alcohol' → only render when user.trackAlcohol is true (Change Round 3, item 1)
//   special — 'celebration' (#13, 365 AFD — landmark screen, NO cash/bank details),
//             'milestone', 'ultimate' (#499), 'grandmaster' (#500)
//
// Category counts: AFD:13  CHECKIN:20  NUTRITION:61  WORKOUT:80  SLEEP:25  MIND:42  BODY:25  HYDRATION:15  ALCOHOL:30  GOALS:30  ENGAGEMENT:32  SOCIAL:15  SEASONAL:25  DISCIPLINE:20  FUN:28  LIFETIME:20  WILDCARD:19  (total 500)

// New glyphs introduced for the 500-badge library — MERGE into badges.jsx BADGE_GLYPHS.
// (Existing keys reused: flame, dumbbell, mountain, star, crown, shield, moon, sun, heart,
//  book, cake, trophy, bolt, calendar, noDrink, pulse, scales, diamond, hexagon, sparkle,
//  arrowUp, target, feather, rocket.)
const BL_NEW_GLYPHS = {
  droplet:  <svg viewBox="0 0 24 24" width="100%" height="100%"><path d="M12 3 C12 3 5 11 5 15 A7 7 0 0 0 19 15 C19 11 12 3 12 3 Z" fill="currentColor" /></svg>,
  leaf:     <svg viewBox="0 0 24 24" width="100%" height="100%"><path d="M20 4 C10 4 4 10 4 20 C14 20 20 14 20 4 Z" fill="currentColor" /><path d="M7 17 C10 13 14 9 17 7" stroke="rgba(0,0,0,.35)" strokeWidth="1.3" fill="none" strokeLinecap="round" /></svg>,
  plate:    <svg viewBox="0 0 24 24" width="100%" height="100%"><circle cx="13.5" cy="12" r="7" fill="none" stroke="currentColor" strokeWidth="2" /><circle cx="13.5" cy="12" r="2.6" fill="currentColor" /><rect x="3" y="4" width="1.8" height="16" rx="0.9" fill="currentColor" /></svg>,
  people:   <svg viewBox="0 0 24 24" width="100%" height="100%"><circle cx="8" cy="8" r="3" fill="currentColor" /><circle cx="16" cy="8" r="3" fill="currentColor" /><path d="M2 20 C2 15.5 4.6 13 8 13 C11.4 13 14 15.5 14 20 Z" fill="currentColor" /><path d="M11.5 20 C11.5 15.5 13 13 16 13 C19.4 13 22 15.5 22 20 Z" fill="currentColor" /></svg>,
  brain:    <svg viewBox="0 0 24 24" width="100%" height="100%"><path d="M9 4 C6.2 4 5 6.6 6.2 8 C4.2 9 4.2 12 6.2 13 C5.2 15.2 7.4 17.6 10 16.6 L10 5 C10 4.4 9.6 4 9 4 Z" fill="currentColor" /><path d="M15 4 C17.8 4 19 6.6 17.8 8 C19.8 9 19.8 12 17.8 13 C18.8 15.2 16.6 17.6 14 16.6 L14 5 C14 4.4 14.4 4 15 4 Z" fill="currentColor" /></svg>,
  ruler:    <svg viewBox="0 0 24 24" width="100%" height="100%"><rect x="2" y="7" width="20" height="10" rx="1.6" fill="currentColor" /><g stroke="#0A0A0C" strokeWidth="1.3" strokeLinecap="round"><line x1="6" y1="7" x2="6" y2="12" /><line x1="10" y1="7" x2="10" y2="13" /><line x1="14" y1="7" x2="14" y2="12" /><line x1="18" y1="7" x2="18" y2="13" /></g></svg>,
  steps:    <svg viewBox="0 0 24 24" width="100%" height="100%"><ellipse cx="8" cy="8.5" rx="2.8" ry="4.3" fill="currentColor" /><ellipse cx="16" cy="15.5" rx="2.8" ry="4.3" fill="currentColor" /></svg>,
  run:      <svg viewBox="0 0 24 24" width="100%" height="100%"><circle cx="15.5" cy="5" r="2.4" fill="currentColor" /><path d="M14 8 L9.5 11.5 L13 14 L11 20 M13 14 L17.5 15.5 L19.5 12 M9.5 11.5 L5 13 M14.5 8.5 L18.5 9.5" stroke="currentColor" strokeWidth="2" fill="none" strokeLinecap="round" strokeLinejoin="round" /></svg>,
  bike:     <svg viewBox="0 0 24 24" width="100%" height="100%"><circle cx="6" cy="17" r="3.4" fill="none" stroke="currentColor" strokeWidth="2" /><circle cx="18" cy="17" r="3.4" fill="none" stroke="currentColor" strokeWidth="2" /><path d="M6 17 L10 9 L16 9 M10 9 L13 17 M13 17 L18 17 M14 6 L17 6" stroke="currentColor" strokeWidth="2" fill="none" strokeLinecap="round" strokeLinejoin="round" /></svg>,
  swim:     <svg viewBox="0 0 24 24" width="100%" height="100%"><circle cx="7" cy="8" r="2.3" fill="currentColor" /><path d="M3 13 L9 11 L13 13 L17.5 10" stroke="currentColor" strokeWidth="2" fill="none" strokeLinecap="round" strokeLinejoin="round" /><path d="M2 18 Q5 16 8 18 T14 18 T20 18" stroke="currentColor" strokeWidth="1.6" fill="none" /></svg>,
  camera:   <svg viewBox="0 0 24 24" width="100%" height="100%"><rect x="2" y="7" width="20" height="13" rx="2.5" fill="currentColor" /><circle cx="12" cy="13.5" r="3.6" fill="#0A0A0C" /><rect x="8" y="4" width="8" height="3.2" rx="1.2" fill="currentColor" /></svg>,
  snowflake:<svg viewBox="0 0 24 24" width="100%" height="100%"><g stroke="currentColor" strokeWidth="1.8" strokeLinecap="round"><line x1="12" y1="2" x2="12" y2="22" /><line x1="3.3" y1="7" x2="20.7" y2="17" /><line x1="20.7" y1="7" x2="3.3" y2="17" /><path d="M12 5 L9.4 6.6 M12 5 L14.6 6.6 M12 19 L9.4 17.4 M12 19 L14.6 17.4" /></g></svg>,
  medal:    <svg viewBox="0 0 24 24" width="100%" height="100%"><path d="M8 2 L11 9 L7 9 Z M16 2 L13 9 L17 9 Z" fill="currentColor" /><circle cx="12" cy="15.5" r="6" fill="currentColor" /><circle cx="12" cy="15.5" r="2.6" fill="#0A0A0C" /></svg>,
};

const BADGE_LIB_CATEGORIES = [
  { key: "AFD", label: "AFD Streaks", count: 13, gate: "alcohol" },
  { key: "CHECKIN", label: "Check-In", count: 20 },
  { key: "NUTRITION", label: "Nutrition", count: 61 },
  { key: "WORKOUT", label: "Workout", count: 80 },
  { key: "SLEEP", label: "Sleep", count: 25 },
  { key: "MIND", label: "Mind", count: 42 },
  { key: "BODY", label: "Body", count: 25 },
  { key: "HYDRATION", label: "Hydration", count: 15 },
  { key: "ALCOHOL", label: "Alcohol", count: 30, gate: "alcohol" },
  { key: "GOALS", label: "Goals", count: 30 },
  { key: "ENGAGEMENT", label: "Engagement", count: 32 },
  { key: "SOCIAL", label: "Social", count: 15 },
  { key: "SEASONAL", label: "Seasonal", count: 25 },
  { key: "DISCIPLINE", label: "Discipline", count: 20 },
  { key: "FUN", label: "Fun", count: 28 },
  { key: "LIFETIME", label: "Lifetime", count: 20 },
  { key: "WILDCARD", label: "Wildcard", count: 19 },
];

const BADGE_LIBRARY = [
  { id: "b001-first-step", n: 1, cat: "AFD", glyph: "steps", track: "nips", gate: "alcohol", name: "First Step", cond: "1 AFD" },
  { id: "b002-triple", n: 2, cat: "AFD", glyph: "noDrink", track: "nips", gate: "alcohol", name: "Triple", cond: "3 AFDs" },
  { id: "b003-nearly-a-week", n: 3, cat: "AFD", glyph: "noDrink", track: "nips", gate: "alcohol", name: "Nearly a Week", cond: "6 AFDs" },
  { id: "b004-one-week-clean", n: 4, cat: "AFD", glyph: "noDrink", track: "nips", gate: "alcohol", name: "One Week Clean", cond: "7 consecutive AFDs" },
  { id: "b005-fortnight", n: 5, cat: "AFD", glyph: "noDrink", track: "nips", gate: "alcohol", name: "Fortnight", cond: "14 consecutive AFDs" },
  { id: "b006-three-weeks", n: 6, cat: "AFD", glyph: "noDrink", track: "nips", gate: "alcohol", name: "Three Weeks", cond: "21 consecutive AFDs" },
  { id: "b007-one-month", n: 7, cat: "AFD", glyph: "noDrink", track: "nips", gate: "alcohol", name: "One Month", cond: "30 consecutive AFDs" },
  { id: "b008-two-months", n: 8, cat: "AFD", glyph: "noDrink", track: "nips", gate: "alcohol", name: "Two Months", cond: "60 consecutive AFDs" },
  { id: "b009-ninety-days", n: 9, cat: "AFD", glyph: "noDrink", track: "nips", gate: "alcohol", name: "Ninety Days", cond: "90 consecutive AFDs" },
  { id: "b010-four-months", n: 10, cat: "AFD", glyph: "noDrink", track: "nips", gate: "alcohol", name: "Four Months", cond: "120 consecutive AFDs" },
  { id: "b011-half-year", n: 11, cat: "AFD", glyph: "noDrink", track: "nips", gate: "alcohol", name: "Half Year", cond: "180 consecutive AFDs" },
  { id: "b012-eight-months", n: 12, cat: "AFD", glyph: "noDrink", track: "nips", gate: "alcohol", name: "Eight Months", cond: "240 consecutive AFDs" },
  { id: "b013-365", n: 13, cat: "AFD", glyph: "noDrink", track: "nips", gate: "alcohol", special: "celebration", name: "365", cond: "365 consecutive AFDs" },
  { id: "b014-first-check-in", n: 14, cat: "CHECKIN", glyph: "flame", track: "checkins", name: "First Check-In", cond: "Complete your first daily check-in" },
  { id: "b015-three-days-straight", n: 15, cat: "CHECKIN", glyph: "flame", track: "checkins", name: "Three Days Straight", cond: "3-day check-in streak" },
  { id: "b016-one-week-streak", n: 16, cat: "CHECKIN", glyph: "flame", track: "checkins", name: "One Week Streak", cond: "7-day check-in streak" },
  { id: "b017-fortnight-streak", n: 17, cat: "CHECKIN", glyph: "flame", track: "checkins", name: "Fortnight Streak", cond: "14-day check-in streak" },
  { id: "b018-twenty-one-days", n: 18, cat: "CHECKIN", glyph: "flame", track: "checkins", name: "Twenty-One Days", cond: "21-day check-in streak" },
  { id: "b019-one-month-streak", n: 19, cat: "CHECKIN", glyph: "flame", track: "checkins", name: "One Month Streak", cond: "30-day check-in streak" },
  { id: "b020-forty-five-days", n: 20, cat: "CHECKIN", glyph: "flame", track: "checkins", name: "Forty-Five Days", cond: "45-day check-in streak" },
  { id: "b021-two-months-straight", n: 21, cat: "CHECKIN", glyph: "flame", track: "checkins", name: "Two Months Straight", cond: "60-day check-in streak" },
  { id: "b022-ninety-day-streak", n: 22, cat: "CHECKIN", glyph: "flame", track: "checkins", name: "Ninety Day Streak", cond: "90-day check-in streak" },
  { id: "b023-one-twenty", n: 23, cat: "CHECKIN", glyph: "flame", track: "checkins", name: "One Twenty", cond: "120-day check-in streak" },
  { id: "b024-half-year-streak", n: 24, cat: "CHECKIN", glyph: "flame", track: "checkins", name: "Half Year Streak", cond: "180-day check-in streak" },
  { id: "b025-nine-months", n: 25, cat: "CHECKIN", glyph: "flame", track: "checkins", name: "Nine Months", cond: "270-day check-in streak" },
  { id: "b026-one-year-streak", n: 26, cat: "CHECKIN", glyph: "flame", track: "checkins", name: "One Year Streak", cond: "365-day check-in streak" },
  { id: "b027-early-bird", n: 27, cat: "CHECKIN", glyph: "flame", track: "checkins", name: "Early Bird", cond: "Check in before 7am 10 times" },
  { id: "b028-night-owl", n: 28, cat: "CHECKIN", glyph: "flame", track: "checkins", name: "Night Owl", cond: "Check in after 9pm 10 times" },
  { id: "b029-consistent", n: 29, cat: "CHECKIN", glyph: "medal", track: "checkins", name: "Consistent", cond: "Check in at the same time 7 days in a row" },
  { id: "b030-weekend-warrior", n: 30, cat: "CHECKIN", glyph: "calendar", track: "checkins", name: "Weekend Warrior", cond: "Check in every Saturday and Sunday for a month" },
  { id: "b031-no-excuses", n: 31, cat: "CHECKIN", glyph: "cake", track: "checkins", name: "No Excuses", cond: "Check in on a public holiday" },
  { id: "b032-travel-check-in", n: 32, cat: "CHECKIN", glyph: "flame", track: "checkins", name: "Travel Check-In", cond: "Check in from a different location" },
  { id: "b033-perfect-month", n: 33, cat: "CHECKIN", glyph: "flame", track: "checkins", name: "Perfect Month", cond: "Check in every single day of a calendar month" },
  { id: "b034-first-meal-logged", n: 34, cat: "NUTRITION", glyph: "plate", track: "food", name: "First Meal Logged", cond: "Log your first meal" },
  { id: "b035-calorie-goal-hit", n: 35, cat: "NUTRITION", glyph: "plate", track: "food", name: "Calorie Goal Hit", cond: "Hit your daily calorie target for the first time" },
  { id: "b036-three-days-on-target", n: 36, cat: "NUTRITION", glyph: "plate", track: "food", name: "Three Days On Target", cond: "Hit calorie goal 3 days in a row" },
  { id: "b037-one-week-on-target", n: 37, cat: "NUTRITION", glyph: "plate", track: "food", name: "One Week On Target", cond: "Hit calorie goal 7 days in a row" },
  { id: "b038-fortnight-on-target", n: 38, cat: "NUTRITION", glyph: "plate", track: "food", name: "Fortnight On Target", cond: "14 days hitting calorie goal" },
  { id: "b039-thirty-days-on-target", n: 39, cat: "NUTRITION", glyph: "plate", track: "food", name: "Thirty Days On Target", cond: "30 days hitting calorie goal" },
  { id: "b040-protein-king", n: 40, cat: "NUTRITION", glyph: "plate", track: "food", name: "Protein King", cond: "Hit protein target 7 days in a row" },
  { id: "b041-protein-machine", n: 41, cat: "NUTRITION", glyph: "plate", track: "food", name: "Protein Machine", cond: "Hit protein target 30 days in a row" },
  { id: "b042-breakfast-champion", n: 42, cat: "NUTRITION", glyph: "plate", track: "food", name: "Breakfast Champion", cond: "Log breakfast 7 days in a row" },
  { id: "b043-lunch-legend", n: 43, cat: "NUTRITION", glyph: "plate", track: "food", name: "Lunch Legend", cond: "Log lunch 7 days in a row" },
  { id: "b044-dinner-done", n: 44, cat: "NUTRITION", glyph: "plate", track: "food", name: "Dinner Done", cond: "Log dinner 7 days in a row" },
  { id: "b045-all-three", n: 45, cat: "NUTRITION", glyph: "plate", track: "food", name: "All Three", cond: "Log all three meals in one day" },
  { id: "b046-perfect-day", n: 46, cat: "NUTRITION", glyph: "plate", track: "food", name: "Perfect Day", cond: "Log all meals and hit calorie + protein targets in one day" },
  { id: "b047-perfect-week", n: 47, cat: "NUTRITION", glyph: "medal", track: "food", name: "Perfect Week", cond: "Perfect day 7 days in a row" },
  { id: "b048-perfect-month", n: 48, cat: "NUTRITION", glyph: "medal", track: "food", name: "Perfect Month", cond: "Perfect day 30 days in a row" },
  { id: "b049-hydrated", n: 49, cat: "NUTRITION", glyph: "droplet", track: "food", name: "Hydrated", cond: "Log 2L+ water in a day" },
  { id: "b050-water-week", n: 50, cat: "NUTRITION", glyph: "droplet", track: "food", name: "Water Week", cond: "Log 2L+ water 7 days in a row" },
  { id: "b051-water-month", n: 51, cat: "NUTRITION", glyph: "droplet", track: "food", name: "Water Month", cond: "Log 2L+ water 30 days in a row" },
  { id: "b052-no-junk", n: 52, cat: "NUTRITION", glyph: "plate", track: "food", name: "No Junk", cond: "Log zero junk food for a week" },
  { id: "b053-meal-prep-mode", n: 53, cat: "NUTRITION", glyph: "plate", track: "food", name: "Meal Prep Mode", cond: "Log the same healthy meal 5 times" },
  { id: "b054-variety-pack", n: 54, cat: "NUTRITION", glyph: "leaf", track: "food", name: "Variety Pack", cond: "Log 10 different foods in one day" },
  { id: "b055-green-day", n: 55, cat: "NUTRITION", glyph: "leaf", track: "food", name: "Green Day", cond: "Log 3+ servings of vegetables in a day" },
  { id: "b056-green-week", n: 56, cat: "NUTRITION", glyph: "leaf", track: "food", name: "Green Week", cond: "Log 3+ servings of vegetables 7 days in a row" },
  { id: "b057-fruit-first", n: 57, cat: "NUTRITION", glyph: "leaf", track: "food", name: "Fruit First", cond: "Log fruit before 9am 5 times" },
  { id: "b058-under-budget", n: 58, cat: "NUTRITION", glyph: "plate", track: "food", name: "Under Budget", cond: "Come in under calorie target by less than 100cal 7 days in a row" },
  { id: "b059-snack-smart", n: 59, cat: "NUTRITION", glyph: "plate", track: "food", name: "Snack Smart", cond: "Log a healthy snack 14 days in a row" },
  { id: "b060-big-breakfast", n: 60, cat: "NUTRITION", glyph: "plate", track: "food", name: "Big Breakfast", cond: "Log a breakfast over 40g protein" },
  { id: "b061-no-sugar-day", n: 61, cat: "NUTRITION", glyph: "plate", track: "food", name: "No Sugar Day", cond: "Log a day with zero added sugar" },
  { id: "b062-no-sugar-week", n: 62, cat: "NUTRITION", glyph: "plate", track: "food", name: "No Sugar Week", cond: "7 days with zero added sugar" },
  { id: "b063-fibre-focus", n: 63, cat: "NUTRITION", glyph: "plate", track: "food", name: "Fibre Focus", cond: "Log 25g+ fibre in a day" },
  { id: "b064-balanced-plate", n: 64, cat: "NUTRITION", glyph: "leaf", track: "food", name: "Balanced Plate", cond: "Hit all macros within range in one day" },
  { id: "b065-balanced-week", n: 65, cat: "NUTRITION", glyph: "flame", track: "food", name: "Balanced Week", cond: "Hit all macros every day for 7 days" },
  { id: "b066-meal-logger", n: 66, cat: "NUTRITION", glyph: "plate", track: "food", name: "Meal Logger", cond: "Log 100 total meals" },
  { id: "b067-meal-machine", n: 67, cat: "NUTRITION", glyph: "plate", track: "food", name: "Meal Machine", cond: "Log 500 total meals" },
  { id: "b068-meal-master", n: 68, cat: "NUTRITION", glyph: "plate", track: "food", name: "Meal Master", cond: "Log 1000 total meals" },
  { id: "b069-calorie-counted", n: 69, cat: "NUTRITION", glyph: "plate", track: "food", name: "Calorie Counted", cond: "Log calories for 50 total days" },
  { id: "b070-nutrition-nerd", n: 70, cat: "NUTRITION", glyph: "plate", track: "food", name: "Nutrition Nerd", cond: "Log calories for 100 total days" },
  { id: "b071-food-diary-legend", n: 71, cat: "NUTRITION", glyph: "plate", track: "food", name: "Food Diary Legend", cond: "Log calories for 365 total days" },
  { id: "b072-low-sodium", n: 72, cat: "NUTRITION", glyph: "plate", track: "food", name: "Low Sodium", cond: "Log a day under 1500mg sodium" },
  { id: "b073-anti-inflammatory", n: 73, cat: "NUTRITION", glyph: "leaf", track: "food", name: "Anti-Inflammatory", cond: "Log turmeric, ginger or omega-3 rich food in one day" },
  { id: "b074-iron-man", n: 74, cat: "NUTRITION", glyph: "plate", track: "food", name: "Iron Man", cond: "Log an iron-rich meal 7 days in a row" },
  { id: "b075-calcium-champion", n: 75, cat: "NUTRITION", glyph: "plate", track: "food", name: "Calcium Champion", cond: "Hit calcium target 7 days in a row" },
  { id: "b076-supplement-streak", n: 76, cat: "NUTRITION", glyph: "plate", track: "food", name: "Supplement Streak", cond: "Log supplements 14 days in a row" },
  { id: "b077-pre-workout-fuelled", n: 77, cat: "NUTRITION", glyph: "plate", track: "food", name: "Pre-Workout Fuelled", cond: "Log a pre-workout meal before exercise 10 times" },
  { id: "b078-post-workout-fuelled", n: 78, cat: "NUTRITION", glyph: "plate", track: "food", name: "Post-Workout Fuelled", cond: "Log a post-workout meal within 1hr of exercise 10 times" },
  { id: "b079-intermittent-faster", n: 79, cat: "NUTRITION", glyph: "plate", track: "food", name: "Intermittent Faster", cond: "Log eating window under 8hrs for 7 days" },
  { id: "b080-clean-eating-week", n: 80, cat: "NUTRITION", glyph: "plate", track: "food", name: "Clean Eating Week", cond: "Log zero processed food for 7 days" },
  { id: "b081-clean-eating-month", n: 81, cat: "NUTRITION", glyph: "plate", track: "food", name: "Clean Eating Month", cond: "Log zero processed food for 30 days" },
  { id: "b082-mindful-eater", n: 82, cat: "NUTRITION", glyph: "plate", track: "food", name: "Mindful Eater", cond: "Complete meal reflection question 14 days in a row" },
  { id: "b083-consistent-eater", n: 83, cat: "NUTRITION", glyph: "plate", track: "food", name: "Consistent Eater", cond: "Log meals within the same 2hr window each day for 7 days" },
  { id: "b084-night-fast", n: 84, cat: "NUTRITION", glyph: "plate", track: "food", name: "Night Fast", cond: "No food logged after 8pm for 7 days in a row" },
  { id: "b085-morning-fast", n: 85, cat: "NUTRITION", glyph: "plate", track: "food", name: "Morning Fast", cond: "No food logged before 10am for 7 days in a row" },
  { id: "b086-cafe-free", n: 86, cat: "NUTRITION", glyph: "plate", track: "food", name: "Cafe Free", cond: "No cafe meals logged for 14 days" },
  { id: "b087-home-cook", n: 87, cat: "NUTRITION", glyph: "plate", track: "food", name: "Home Cook", cond: "Log home-cooked meals only for 7 days" },
  { id: "b088-bbq-badge", n: 88, cat: "NUTRITION", glyph: "plate", track: "food", name: "BBQ Badge", cond: "Log a BBQ meal" },
  { id: "b089-pizza-night", n: 89, cat: "NUTRITION", glyph: "plate", track: "food", name: "Pizza Night", cond: "Log pizza (life is balance)" },
  { id: "b090-cheat-day", n: 90, cat: "NUTRITION", glyph: "plate", track: "food", name: "Cheat Day", cond: "Exceed calorie target by 500+ cal" },
  { id: "b091-back-on-track", n: 91, cat: "NUTRITION", glyph: "plate", track: "food", name: "Back on Track", cond: "Log a perfect day the day after a cheat day" },
  { id: "b092-honest-logger", n: 92, cat: "NUTRITION", glyph: "leaf", track: "food", name: "Honest Logger", cond: "Log a day over target without deleting entries" },
  { id: "b093-100-day-logger", n: 93, cat: "NUTRITION", glyph: "flame", track: "food", name: "100 Day Logger", cond: "Log food for 100 cumulative days" },
  { id: "b094-meal-prepper", n: 94, cat: "NUTRITION", glyph: "plate", track: "food", name: "Meal Prepper", cond: "Log a full week of meals prepared and entered in advance on a Sunday" },
  { id: "b095-first-workout", n: 95, cat: "WORKOUT", glyph: "dumbbell", track: "workouts", name: "First Workout", cond: "Complete your first logged workout" },
  { id: "b096-three-workouts", n: 96, cat: "WORKOUT", glyph: "dumbbell", track: "workouts", name: "Three Workouts", cond: "Complete 3 workouts" },
  { id: "b097-ten-workouts", n: 97, cat: "WORKOUT", glyph: "dumbbell", track: "workouts", name: "Ten Workouts", cond: "Complete 10 workouts" },
  { id: "b098-twenty-five-workouts", n: 98, cat: "WORKOUT", glyph: "dumbbell", track: "workouts", name: "Twenty-Five Workouts", cond: "Complete 25 workouts" },
  { id: "b099-fifty-workouts", n: 99, cat: "WORKOUT", glyph: "dumbbell", track: "workouts", name: "Fifty Workouts", cond: "Complete 50 workouts" },
  { id: "b100-one-hundred-workouts", n: 100, cat: "WORKOUT", glyph: "dumbbell", track: "workouts", name: "One Hundred Workouts", cond: "Complete 100 workouts" },
  { id: "b101-two-fifty", n: 101, cat: "WORKOUT", glyph: "dumbbell", track: "workouts", name: "Two Fifty", cond: "Complete 250 workouts" },
  { id: "b102-five-hundred-workouts", n: 102, cat: "WORKOUT", glyph: "dumbbell", track: "workouts", name: "Five Hundred Workouts", cond: "Complete 500 workouts" },
  { id: "b103-workout-week", n: 103, cat: "WORKOUT", glyph: "dumbbell", track: "workouts", name: "Workout Week", cond: "Work out every day for 7 days" },
  { id: "b104-workout-fortnight", n: 104, cat: "WORKOUT", glyph: "dumbbell", track: "workouts", name: "Workout Fortnight", cond: "Work out every day for 14 days" },
  { id: "b105-workout-month", n: 105, cat: "WORKOUT", glyph: "dumbbell", track: "workouts", name: "Workout Month", cond: "Work out every day for 30 days" },
  { id: "b106-three-times-a-week", n: 106, cat: "WORKOUT", glyph: "flame", track: "workouts", name: "Three Times a Week", cond: "Work out 3x/week for 4 weeks in a row" },
  { id: "b107-four-times-a-week", n: 107, cat: "WORKOUT", glyph: "flame", track: "workouts", name: "Four Times a Week", cond: "Work out 4x/week for 4 weeks in a row" },
  { id: "b108-five-days-a-week", n: 108, cat: "WORKOUT", glyph: "flame", track: "workouts", name: "Five Days a Week", cond: "Work out 5x/week for 4 weeks in a row" },
  { id: "b109-monday-momentum", n: 109, cat: "WORKOUT", glyph: "dumbbell", track: "workouts", name: "Monday Momentum", cond: "Work out every Monday for a month" },
  { id: "b110-no-skip-monday", n: 110, cat: "WORKOUT", glyph: "dumbbell", track: "workouts", name: "No Skip Monday", cond: "Never skip Monday for 3 months" },
  { id: "b111-early-riser", n: 111, cat: "WORKOUT", glyph: "dumbbell", track: "workouts", name: "Early Riser", cond: "Work out before 6am 5 times" },
  { id: "b112-lunch-break-legend", n: 112, cat: "WORKOUT", glyph: "plate", track: "workouts", name: "Lunch Break Legend", cond: "Work out between 12-2pm 5 times" },
  { id: "b113-night-shift", n: 113, cat: "WORKOUT", glyph: "dumbbell", track: "workouts", name: "Night Shift", cond: "Work out after 8pm 5 times" },
  { id: "b114-chest-day", n: 114, cat: "WORKOUT", glyph: "ruler", track: "workouts", name: "Chest Day", cond: "Complete a chest-focused workout" },
  { id: "b115-back-attack", n: 115, cat: "WORKOUT", glyph: "dumbbell", track: "workouts", name: "Back Attack", cond: "Complete a back-focused workout" },
  { id: "b116-leg-day", n: 116, cat: "WORKOUT", glyph: "dumbbell", track: "workouts", name: "Leg Day", cond: "Complete a leg workout" },
  { id: "b117-leg-day-twice", n: 117, cat: "WORKOUT", glyph: "dumbbell", track: "workouts", name: "Leg Day Twice", cond: "Complete 2 leg workouts in one week" },
  { id: "b118-shoulder-season", n: 118, cat: "WORKOUT", glyph: "dumbbell", track: "workouts", name: "Shoulder Season", cond: "Complete a shoulder-focused workout" },
  { id: "b119-arm-day", n: 119, cat: "WORKOUT", glyph: "ruler", track: "workouts", name: "Arm Day", cond: "Complete an arms-focused workout" },
  { id: "b120-core-crusher", n: 120, cat: "WORKOUT", glyph: "dumbbell", track: "workouts", name: "Core Crusher", cond: "Complete a core-focused workout" },
  { id: "b121-full-body", n: 121, cat: "WORKOUT", glyph: "dumbbell", track: "workouts", name: "Full Body", cond: "Complete a full-body workout" },
  { id: "b122-push-day", n: 122, cat: "WORKOUT", glyph: "dumbbell", track: "workouts", name: "Push Day", cond: "Complete a push workout" },
  { id: "b123-pull-day", n: 123, cat: "WORKOUT", glyph: "dumbbell", track: "workouts", name: "Pull Day", cond: "Complete a pull workout" },
  { id: "b124-push-pull-legs", n: 124, cat: "WORKOUT", glyph: "dumbbell", track: "workouts", name: "Push Pull Legs", cond: "Complete all three in one week" },
  { id: "b125-cardio-starter", n: 125, cat: "WORKOUT", glyph: "dumbbell", track: "workouts", name: "Cardio Starter", cond: "Complete your first cardio session" },
  { id: "b126-cardio-week", n: 126, cat: "WORKOUT", glyph: "dumbbell", track: "workouts", name: "Cardio Week", cond: "Complete cardio 5 days in a row" },
  { id: "b127-cardio-month", n: 127, cat: "WORKOUT", glyph: "dumbbell", track: "workouts", name: "Cardio Month", cond: "Complete cardio 20 times in a month" },
  { id: "b128-5km-done", n: 128, cat: "WORKOUT", glyph: "run", track: "workouts", name: "5km Done", cond: "Log a 5km run" },
  { id: "b129-10km-done", n: 129, cat: "WORKOUT", glyph: "run", track: "workouts", name: "10km Done", cond: "Log a 10km run" },
  { id: "b130-half-marathon", n: 130, cat: "WORKOUT", glyph: "run", track: "workouts", name: "Half Marathon", cond: "Log 21km" },
  { id: "b131-marathon", n: 131, cat: "WORKOUT", glyph: "run", track: "workouts", name: "Marathon", cond: "Log 42km" },
  { id: "b132-10-000-steps", n: 132, cat: "WORKOUT", glyph: "steps", track: "workouts", name: "10,000 Steps", cond: "Hit 10,000 steps in a day" },
  { id: "b133-step-streak", n: 133, cat: "WORKOUT", glyph: "steps", track: "workouts", name: "Step Streak", cond: "Hit 10,000 steps 7 days in a row" },
  { id: "b134-step-month", n: 134, cat: "WORKOUT", glyph: "steps", track: "workouts", name: "Step Month", cond: "Hit 10,000 steps 30 days in a row" },
  { id: "b135-personal-best", n: 135, cat: "WORKOUT", glyph: "star", track: "workouts", name: "Personal Best", cond: "Log a PB on any exercise" },
  { id: "b136-five-pbs", n: 136, cat: "WORKOUT", glyph: "star", track: "workouts", name: "Five PBs", cond: "Log 5 personal bests" },
  { id: "b137-ten-pbs", n: 137, cat: "WORKOUT", glyph: "star", track: "workouts", name: "Ten PBs", cond: "Log 10 personal bests" },
  { id: "b138-stronger-every-week", n: 138, cat: "WORKOUT", glyph: "star", track: "workouts", name: "Stronger Every Week", cond: "Log a PB each week for 4 weeks" },
  { id: "b139-reeplex-regular", n: 139, cat: "WORKOUT", glyph: "dumbbell", track: "workouts", name: "Reeplex Regular", cond: "Use the workplace gym 10 times" },
  { id: "b140-reeplex-committed", n: 140, cat: "WORKOUT", glyph: "dumbbell", track: "workouts", name: "Reeplex Committed", cond: "Use the workplace gym 50 times" },
  { id: "b141-dumbbell-starter", n: 141, cat: "WORKOUT", glyph: "dumbbell", track: "workouts", name: "Dumbbell Starter", cond: "Complete a dumbbell-only workout" },
  { id: "b142-dumbbell-devotee", n: 142, cat: "WORKOUT", glyph: "dumbbell", track: "workouts", name: "Dumbbell Devotee", cond: "Complete 10 dumbbell-only workouts" },
  { id: "b143-gym-rat", n: 143, cat: "WORKOUT", glyph: "dumbbell", track: "workouts", name: "Gym Rat", cond: "Log 30 gym sessions in a month" },
  { id: "b144-home-gym-hero", n: 144, cat: "WORKOUT", glyph: "dumbbell", track: "workouts", name: "Home Gym Hero", cond: "Complete 25 home gym workouts" },
  { id: "b145-bodyweight-only", n: 145, cat: "WORKOUT", glyph: "ruler", track: "workouts", name: "Bodyweight Only", cond: "Complete a bodyweight-only workout" },
  { id: "b146-stretch-it-out", n: 146, cat: "WORKOUT", glyph: "target", track: "workouts", name: "Stretch it Out", cond: "Log a stretching/mobility session" },
  { id: "b147-mobility-month", n: 147, cat: "WORKOUT", glyph: "dumbbell", track: "workouts", name: "Mobility Month", cond: "Log mobility work 12 times in a month" },
  { id: "b148-rest-day-taken", n: 148, cat: "WORKOUT", glyph: "dumbbell", track: "workouts", name: "Rest Day Taken", cond: "Log a deliberate rest day" },
  { id: "b149-active-recovery", n: 149, cat: "WORKOUT", glyph: "dumbbell", track: "workouts", name: "Active Recovery", cond: "Log an active recovery session" },
  { id: "b150-consistency-king", n: 150, cat: "WORKOUT", glyph: "dumbbell", track: "workouts", name: "Consistency King", cond: "Work out at least once every week for 12 weeks straight" },
  { id: "b151-consistency-legend", n: 151, cat: "WORKOUT", glyph: "dumbbell", track: "workouts", name: "Consistency Legend", cond: "Work out at least once every week for 52 weeks straight" },
  { id: "b152-volume-king", n: 152, cat: "WORKOUT", glyph: "star", track: "workouts", name: "Volume King", cond: "Log 10,000kg total lifted in one session" },
  { id: "b153-iron-total", n: 153, cat: "WORKOUT", glyph: "star", track: "workouts", name: "Iron Total", cond: "Log 100,000kg total lifted cumulative" },
  { id: "b154-sweat-session", n: 154, cat: "WORKOUT", glyph: "dumbbell", track: "workouts", name: "Sweat Session", cond: "Log a workout over 60 minutes" },
  { id: "b155-quick-fire", n: 155, cat: "WORKOUT", glyph: "dumbbell", track: "workouts", name: "Quick Fire", cond: "Complete a workout in under 20 minutes" },
  { id: "b156-no-excuses-workout", n: 156, cat: "WORKOUT", glyph: "dumbbell", track: "workouts", name: "No Excuses Workout", cond: "Work out while travelling" },
  { id: "b157-outdoor-session", n: 157, cat: "WORKOUT", glyph: "dumbbell", track: "workouts", name: "Outdoor Session", cond: "Log an outdoor workout" },
  { id: "b158-swim-session", n: 158, cat: "WORKOUT", glyph: "swim", track: "workouts", name: "Swim Session", cond: "Log a swim workout" },
  { id: "b159-bike-ride", n: 159, cat: "WORKOUT", glyph: "bike", track: "workouts", name: "Bike Ride", cond: "Log a cycling session" },
  { id: "b160-sport-played", n: 160, cat: "WORKOUT", glyph: "dumbbell", track: "workouts", name: "Sport Played", cond: "Log a sport/game session" },
  { id: "b161-team-sport", n: 161, cat: "WORKOUT", glyph: "dumbbell", track: "workouts", name: "Team Sport", cond: "Log a team sport session" },
  { id: "b162-solo-grind", n: 162, cat: "WORKOUT", glyph: "dumbbell", track: "workouts", name: "Solo Grind", cond: "Log 10 solo workouts in a row with no rest day" },
  { id: "b163-workout-buddy", n: 163, cat: "WORKOUT", glyph: "people", track: "workouts", name: "Workout Buddy", cond: "Tag another user in a shared workout" },
  { id: "b164-coached-session", n: 164, cat: "WORKOUT", glyph: "dumbbell", track: "workouts", name: "Coached Session", cond: "Log a PT or coached session" },
  { id: "b165-new-exercise", n: 165, cat: "WORKOUT", glyph: "dumbbell", track: "workouts", name: "New Exercise", cond: "Try an exercise for the first time" },
  { id: "b166-exercised-every-month", n: 166, cat: "WORKOUT", glyph: "dumbbell", track: "workouts", name: "Exercised Every Month", cond: "Work out at least once in 12 consecutive months" },
  { id: "b167-comeback", n: 167, cat: "WORKOUT", glyph: "dumbbell", track: "workouts", name: "Comeback", cond: "Log a workout after a 14+ day gap" },
  { id: "b168-never-quit", n: 168, cat: "WORKOUT", glyph: "dumbbell", track: "workouts", name: "Never Quit", cond: "Log a workout after a 30+ day gap" },
  { id: "b169-six-pack-journey", n: 169, cat: "WORKOUT", glyph: "dumbbell", track: "workouts", name: "Six Pack Journey", cond: "Log 90 consecutive days with at least 3 workouts/week" },
  { id: "b170-athlete", n: 170, cat: "WORKOUT", glyph: "dumbbell", track: "workouts", name: "Athlete", cond: "Complete all workout category types in one week" },
  { id: "b171-iron-discipline", n: 171, cat: "WORKOUT", glyph: "plate", track: "workouts", name: "Iron Discipline", cond: "Work out 5x/week for 12 consecutive weeks" },
  { id: "b172-sweat-equity", n: 172, cat: "WORKOUT", glyph: "dumbbell", track: "workouts", name: "Sweat Equity", cond: "Log 500 total workout hours" },
  { id: "b173-moving-every-day", n: 173, cat: "WORKOUT", glyph: "dumbbell", track: "workouts", name: "Moving Every Day", cond: "Log some form of movement every day for 30 days" },
  { id: "b174-beast-mode", n: 174, cat: "WORKOUT", glyph: "dumbbell", track: "workouts", name: "Beast Mode", cond: "Complete a workout rated max intensity" },
  { id: "b175-first-sleep-log", n: 175, cat: "SLEEP", glyph: "moon", track: "sleep", name: "First Sleep Log", cond: "Log your first sleep entry" },
  { id: "b176-eight-hours", n: 176, cat: "SLEEP", glyph: "moon", track: "sleep", name: "Eight Hours", cond: "Log 8+ hours sleep" },
  { id: "b177-sleep-week", n: 177, cat: "SLEEP", glyph: "moon", track: "sleep", name: "Sleep Week", cond: "Log 7+ hours every night for 7 days" },
  { id: "b178-sleep-month", n: 178, cat: "SLEEP", glyph: "moon", track: "sleep", name: "Sleep Month", cond: "Log 7+ hours every night for 30 days" },
  { id: "b179-early-to-bed", n: 179, cat: "SLEEP", glyph: "moon", track: "sleep", name: "Early to Bed", cond: "In bed before 10pm 5 times" },
  { id: "b180-consistent-bedtime", n: 180, cat: "SLEEP", glyph: "moon", track: "sleep", name: "Consistent Bedtime", cond: "Same bedtime (+/-30min) 7 nights in a row" },
  { id: "b181-consistent-wakeup", n: 181, cat: "SLEEP", glyph: "moon", track: "sleep", name: "Consistent Wakeup", cond: "Same wake time (+/-30min) 7 days in a row" },
  { id: "b182-full-routine", n: 182, cat: "SLEEP", glyph: "moon", track: "sleep", name: "Full Routine", cond: "In bed before 10pm + 8hrs sleep + up before 6am in one day" },
  { id: "b183-sleep-streak", n: 183, cat: "SLEEP", glyph: "moon", track: "sleep", name: "Sleep Streak", cond: "Log sleep every day for 14 days" },
  { id: "b184-deep-sleeper", n: 184, cat: "SLEEP", glyph: "moon", track: "sleep", name: "Deep Sleeper", cond: "Log a sleep quality score of 9/10 or above" },
  { id: "b185-power-nap", n: 185, cat: "SLEEP", glyph: "moon", track: "sleep", name: "Power Nap", cond: "Log a nap between 15-30 minutes" },
  { id: "b186-no-phone-before-bed", n: 186, cat: "SLEEP", glyph: "moon", track: "sleep", name: "No Phone Before Bed", cond: "Log screen-free hour before bed 7 days in a row" },
  { id: "b187-wind-down", n: 187, cat: "SLEEP", glyph: "moon", track: "sleep", name: "Wind Down", cond: "Complete evening check-in within 1hr of sleep 7 nights" },
  { id: "b188-rise-and-shine", n: 188, cat: "SLEEP", glyph: "moon", track: "sleep", name: "Rise and Shine", cond: "Wake before 5:30am 5 times" },
  { id: "b189-sleep-banker", n: 189, cat: "SLEEP", glyph: "moon", track: "sleep", name: "Sleep Banker", cond: "Average 8.5hrs/night for a full week" },
  { id: "b190-rested", n: 190, cat: "SLEEP", glyph: "moon", track: "sleep", name: "Rested", cond: "Log feeling rested 7 days in a row" },
  { id: "b191-night-routine", n: 191, cat: "SLEEP", glyph: "medal", track: "sleep", name: "Night Routine", cond: "Complete night routine checklist 14 days in a row" },
  { id: "b192-sleep-logger", n: 192, cat: "SLEEP", glyph: "moon", track: "sleep", name: "Sleep Logger", cond: "Log sleep for 50 cumulative nights" },
  { id: "b193-sleep-master", n: 193, cat: "SLEEP", glyph: "moon", track: "sleep", name: "Sleep Master", cond: "Log sleep for 100 cumulative nights" },
  { id: "b194-sleep-champion", n: 194, cat: "SLEEP", glyph: "moon", track: "sleep", name: "Sleep Champion", cond: "Log sleep for 365 cumulative nights" },
  { id: "b195-weekend-sleep", n: 195, cat: "SLEEP", glyph: "moon", track: "sleep", name: "Weekend Sleep", cond: "Log 9+ hours on a Saturday or Sunday" },
  { id: "b196-catch-up", n: 196, cat: "SLEEP", glyph: "moon", track: "sleep", name: "Catch Up", cond: "Log 9+ hours the night after a late night" },
  { id: "b197-no-alarm", n: 197, cat: "SLEEP", glyph: "moon", track: "sleep", name: "No Alarm", cond: "Log waking naturally 5 times" },
  { id: "b198-perfect-sleep-week", n: 198, cat: "SLEEP", glyph: "moon", track: "sleep", name: "Perfect Sleep Week", cond: "Hit sleep target every night + feel rested every morning for 7 days" },
  { id: "b199-lights-out", n: 199, cat: "SLEEP", glyph: "moon", track: "sleep", name: "Lights Out", cond: "No screen time logged after 9pm for 7 nights in a row" },
  { id: "b200-first-journal", n: 200, cat: "MIND", glyph: "feather", track: "mind", name: "First Journal", cond: "Complete your first journal entry" },
  { id: "b201-three-day-journal", n: 201, cat: "MIND", glyph: "feather", track: "mind", name: "Three Day Journal", cond: "Journal 3 days in a row" },
  { id: "b202-journal-week", n: 202, cat: "MIND", glyph: "feather", track: "mind", name: "Journal Week", cond: "Journal 7 days in a row" },
  { id: "b203-journal-month", n: 203, cat: "MIND", glyph: "feather", track: "mind", name: "Journal Month", cond: "Journal 30 days in a row" },
  { id: "b204-journal-year", n: 204, cat: "MIND", glyph: "feather", track: "mind", name: "Journal Year", cond: "Journal 365 cumulative days" },
  { id: "b205-gratitude-starter", n: 205, cat: "MIND", glyph: "brain", track: "mind", name: "Gratitude Starter", cond: "Log your first gratitude entry" },
  { id: "b206-grateful-week", n: 206, cat: "MIND", glyph: "medal", track: "mind", name: "Grateful Week", cond: "Log gratitude 7 days in a row" },
  { id: "b207-grateful-month", n: 207, cat: "MIND", glyph: "medal", track: "mind", name: "Grateful Month", cond: "Log gratitude 30 days in a row" },
  { id: "b208-stress-score-low", n: 208, cat: "MIND", glyph: "brain", track: "mind", name: "Stress Score Low", cond: "Log a stress level of 2/10 or below" },
  { id: "b209-stress-free-week", n: 209, cat: "MIND", glyph: "brain", track: "mind", name: "Stress Free Week", cond: "Log stress below 4/10 every day for 7 days" },
  { id: "b210-mood-tracker", n: 210, cat: "MIND", glyph: "heart", track: "mind", name: "Mood Tracker", cond: "Log mood for 14 consecutive days" },
  { id: "b211-mood-month", n: 211, cat: "MIND", glyph: "heart", track: "mind", name: "Mood Month", cond: "Log mood for 30 consecutive days" },
  { id: "b212-good-vibes", n: 212, cat: "MIND", glyph: "heart", track: "mind", name: "Good Vibes", cond: "Log a mood score of 9/10 or above" },
  { id: "b213-positive-week", n: 213, cat: "MIND", glyph: "heart", track: "mind", name: "Positive Week", cond: "Log mood 7/10 or above every day for 7 days" },
  { id: "b214-bounce-back", n: 214, cat: "MIND", glyph: "heart", track: "mind", name: "Bounce Back", cond: "Log a high mood score the day after a low one" },
  { id: "b215-meditation-starter", n: 215, cat: "MIND", glyph: "brain", track: "mind", name: "Meditation Starter", cond: "Log your first meditation session" },
  { id: "b216-meditation-week", n: 216, cat: "MIND", glyph: "brain", track: "mind", name: "Meditation Week", cond: "Meditate 7 days in a row" },
  { id: "b217-meditation-month", n: 217, cat: "MIND", glyph: "brain", track: "mind", name: "Meditation Month", cond: "Meditate 30 days in a row" },
  { id: "b218-ten-minutes", n: 218, cat: "MIND", glyph: "brain", track: "mind", name: "Ten Minutes", cond: "Meditate for 10+ minutes in one session" },
  { id: "b219-mindful-moment", n: 219, cat: "MIND", glyph: "brain", track: "mind", name: "Mindful Moment", cond: "Complete a breathing exercise" },
  { id: "b220-breathing-streak", n: 220, cat: "MIND", glyph: "brain", track: "mind", name: "Breathing Streak", cond: "Complete a breathing exercise 7 days in a row" },
  { id: "b221-cold-exposure", n: 221, cat: "MIND", glyph: "snowflake", track: "mind", name: "Cold Exposure", cond: "Log a cold shower" },
  { id: "b222-cold-streak", n: 222, cat: "MIND", glyph: "snowflake", track: "mind", name: "Cold Streak", cond: "Log cold shower 7 days in a row" },
  { id: "b223-sunlight-first", n: 223, cat: "MIND", glyph: "sun", track: "mind", name: "Sunlight First", cond: "Log morning sunlight exposure 7 days in a row" },
  { id: "b224-phone-free-morning", n: 224, cat: "MIND", glyph: "medal", track: "mind", name: "Phone Free Morning", cond: "Log no phone use before 8am 5 days in a row" },
  { id: "b225-no-scroll", n: 225, cat: "MIND", glyph: "people", track: "mind", name: "No Scroll", cond: "Log a social media free day" },
  { id: "b226-digital-detox", n: 226, cat: "MIND", glyph: "people", track: "mind", name: "Digital Detox", cond: "Log 3 social media free days in a week" },
  { id: "b227-read-today", n: 227, cat: "MIND", glyph: "book", track: "mind", name: "Read Today", cond: "Log reading for 7 days in a row" },
  { id: "b228-10-pages", n: 228, cat: "MIND", glyph: "book", track: "mind", name: "10 Pages", cond: "Log reading 10+ pages in a day" },
  { id: "b229-book-finished", n: 229, cat: "MIND", glyph: "book", track: "mind", name: "Book Finished", cond: "Log completing a book" },
  { id: "b230-five-books", n: 230, cat: "MIND", glyph: "book", track: "mind", name: "Five Books", cond: "Log completing 5 books" },
  { id: "b231-podcast-listener", n: 231, cat: "MIND", glyph: "book", track: "mind", name: "Podcast Listener", cond: "Log a podcast/audio learning session" },
  { id: "b232-learning-streak", n: 232, cat: "MIND", glyph: "book", track: "mind", name: "Learning Streak", cond: "Log learning activity 14 days in a row" },
  { id: "b233-positive-self-talk", n: 233, cat: "MIND", glyph: "brain", track: "mind", name: "Positive Self-Talk", cond: "Complete a self-affirmation check-in 7 days in a row" },
  { id: "b234-therapy-session", n: 234, cat: "MIND", glyph: "brain", track: "mind", name: "Therapy Session", cond: "Log a coaching or therapy session" },
  { id: "b235-five-sessions", n: 235, cat: "MIND", glyph: "brain", track: "mind", name: "Five Sessions", cond: "Log 5 coaching/therapy sessions" },
  { id: "b236-goal-setter", n: 236, cat: "MIND", glyph: "target", track: "mind", name: "Goal Setter", cond: "Set your first goal in the app" },
  { id: "b237-goal-achieved", n: 237, cat: "MIND", glyph: "target", track: "mind", name: "Goal Achieved", cond: "Mark your first goal complete" },
  { id: "b238-five-goals", n: 238, cat: "MIND", glyph: "target", track: "mind", name: "Five Goals", cond: "Complete 5 goals" },
  { id: "b239-ten-goals", n: 239, cat: "MIND", glyph: "target", track: "mind", name: "Ten Goals", cond: "Complete 10 goals" },
  { id: "b240-vision-board", n: 240, cat: "MIND", glyph: "feather", track: "mind", name: "Vision Board", cond: "Complete the vision/values section of your profile" },
  { id: "b241-screen-free-sunday", n: 241, cat: "MIND", glyph: "people", track: "mind", name: "Screen Free Sunday", cond: "Log zero social media and no streaming on a Sunday" },
  { id: "b242-first-measurement", n: 242, cat: "BODY", glyph: "ruler", track: "measurements", name: "First Measurement", cond: "Log your first body measurement" },
  { id: "b243-measurement-month", n: 243, cat: "BODY", glyph: "ruler", track: "measurements", name: "Measurement Month", cond: "Log measurements for 30 consecutive days" },
  { id: "b244-measurement-streak", n: 244, cat: "BODY", glyph: "ruler", track: "measurements", name: "Measurement Streak", cond: "Log measurements 7 days in a row" },
  { id: "b245-first-progress-photo", n: 245, cat: "BODY", glyph: "camera", track: "measurements", name: "First Progress Photo", cond: "Upload your first progress photo" },
  { id: "b246-photo-month", n: 246, cat: "BODY", glyph: "camera", track: "measurements", name: "Photo Month", cond: "Upload a progress photo every week for a month" },
  { id: "b247-before-and-after", n: 247, cat: "BODY", glyph: "camera", track: "measurements", name: "Before and After", cond: "Upload photos at least 90 days apart" },
  { id: "b248-consistent-tracker", n: 248, cat: "BODY", glyph: "camera", track: "measurements", name: "Consistent Tracker", cond: "Log measurements + photo on the same day 4 weeks in a row" },
  { id: "b249-lost-first-kilo", n: 249, cat: "BODY", glyph: "ruler", track: "measurements", name: "Lost First Kilo", cond: "Log a 1kg reduction in body weight" },
  { id: "b250-lost-five-kilos", n: 250, cat: "BODY", glyph: "ruler", track: "measurements", name: "Lost Five Kilos", cond: "Log a 5kg reduction in body weight" },
  { id: "b251-lost-ten-kilos", n: 251, cat: "BODY", glyph: "ruler", track: "measurements", name: "Lost Ten Kilos", cond: "Log a 10kg reduction in body weight" },
  { id: "b252-gained-first-kilo", n: 252, cat: "BODY", glyph: "ruler", track: "measurements", name: "Gained First Kilo", cond: "Log a 1kg increase (for those bulking)" },
  { id: "b253-waist-down", n: 253, cat: "BODY", glyph: "ruler", track: "measurements", name: "Waist Down", cond: "Log a reduction in waist measurement" },
  { id: "b254-arm-growth", n: 254, cat: "BODY", glyph: "ruler", track: "measurements", name: "Arm Growth", cond: "Log an increase in arm measurement" },
  { id: "b255-chest-gains", n: 255, cat: "BODY", glyph: "ruler", track: "measurements", name: "Chest Gains", cond: "Log an increase in chest measurement" },
  { id: "b256-body-fat-drop", n: 256, cat: "BODY", glyph: "ruler", track: "measurements", name: "Body Fat Drop", cond: "Log a reduction in body fat %" },
  { id: "b257-weigh-in-streak", n: 257, cat: "BODY", glyph: "ruler", track: "measurements", name: "Weigh In Streak", cond: "Log weight every day for 14 days" },
  { id: "b258-weigh-in-month", n: 258, cat: "BODY", glyph: "ruler", track: "measurements", name: "Weigh In Month", cond: "Log weight every day for 30 days" },
  { id: "b259-consistent-weigh-in", n: 259, cat: "BODY", glyph: "ruler", track: "measurements", name: "Consistent Weigh-In", cond: "Same time weigh-in 7 days in a row" },
  { id: "b260-bmi-tracked", n: 260, cat: "BODY", glyph: "ruler", track: "measurements", name: "BMI Tracked", cond: "Log height + weight for BMI calculation" },
  { id: "b261-healthy-range", n: 261, cat: "BODY", glyph: "ruler", track: "measurements", name: "Healthy Range", cond: "BMI enters healthy range" },
  { id: "b262-transformation", n: 262, cat: "BODY", glyph: "ruler", track: "measurements", name: "Transformation", cond: "Log a 10%+ change in any measurement over 90 days" },
  { id: "b263-photo-gallery", n: 263, cat: "BODY", glyph: "camera", track: "measurements", name: "Photo Gallery", cond: "Upload 10 progress photos" },
  { id: "b264-body-scanner", n: 264, cat: "BODY", glyph: "ruler", track: "measurements", name: "Body Scanner", cond: "Log all measurement fields in one session" },
  { id: "b265-six-month-check", n: 265, cat: "BODY", glyph: "ruler", track: "measurements", name: "Six Month Check", cond: "Log measurements at 6-month intervals twice" },
  { id: "b266-annual-review", n: 266, cat: "BODY", glyph: "ruler", track: "measurements", name: "Annual Review", cond: "Log measurements 12 months apart" },
  { id: "b267-first-water-log", n: 267, cat: "HYDRATION", glyph: "droplet", track: "water", name: "First Water Log", cond: "Log your first water intake" },
  { id: "b268-two-litres", n: 268, cat: "HYDRATION", glyph: "droplet", track: "water", name: "Two Litres", cond: "Hit 2L in a day" },
  { id: "b269-three-litres", n: 269, cat: "HYDRATION", glyph: "droplet", track: "water", name: "Three Litres", cond: "Hit 3L in a day" },
  { id: "b270-hydration-week", n: 270, cat: "HYDRATION", glyph: "droplet", track: "water", name: "Hydration Week", cond: "Hit 2L+ every day for 7 days" },
  { id: "b271-hydration-month", n: 271, cat: "HYDRATION", glyph: "droplet", track: "water", name: "Hydration Month", cond: "Hit 2L+ every day for 30 days" },
  { id: "b272-morning-water", n: 272, cat: "HYDRATION", glyph: "droplet", track: "water", name: "Morning Water", cond: "Log water within 30 minutes of waking 7 days in a row" },
  { id: "b273-pre-workout-hydrated", n: 273, cat: "HYDRATION", glyph: "droplet", track: "water", name: "Pre-Workout Hydrated", cond: "Log water before every workout for 2 weeks" },
  { id: "b274-water-first", n: 274, cat: "HYDRATION", glyph: "droplet", track: "water", name: "Water First", cond: "Log water as first intake of the day 14 days in a row" },
  { id: "b275-no-soft-drink", n: 275, cat: "HYDRATION", glyph: "droplet", track: "water", name: "No Soft Drink", cond: "Log zero soft drink for 7 days" },
  { id: "b276-no-soft-drink-month", n: 276, cat: "HYDRATION", glyph: "droplet", track: "water", name: "No Soft Drink Month", cond: "Log zero soft drink for 30 days" },
  { id: "b277-electrolyte-day", n: 277, cat: "HYDRATION", glyph: "droplet", track: "water", name: "Electrolyte Day", cond: "Log electrolytes on a heavy workout day" },
  { id: "b278-caffeine-cap", n: 278, cat: "HYDRATION", glyph: "droplet", track: "water", name: "Caffeine Cap", cond: "Stay under 400mg caffeine for 7 days in a row" },
  { id: "b279-herbal-tea", n: 279, cat: "HYDRATION", glyph: "droplet", track: "water", name: "Herbal Tea", cond: "Log herbal tea 7 days in a row" },
  { id: "b280-hydration-hero", n: 280, cat: "HYDRATION", glyph: "droplet", track: "water", name: "Hydration Hero", cond: "Log water intake for 100 cumulative days" },
  { id: "b281-water-champion", n: 281, cat: "HYDRATION", glyph: "droplet", track: "water", name: "Water Champion", cond: "Hit 2L+ for 100 cumulative days" },
  { id: "b282-first-log", n: 282, cat: "ALCOHOL", glyph: "noDrink", track: "nips", gate: "alcohol", name: "First Log", cond: "Log your first drink honestly" },
  { id: "b283-under-target", n: 283, cat: "ALCOHOL", glyph: "noDrink", track: "nips", gate: "alcohol", name: "Under Target", cond: "Come in under weekly target for the first time" },
  { id: "b284-under-target-streak", n: 284, cat: "ALCOHOL", glyph: "flame", track: "nips", gate: "alcohol", name: "Under Target Streak", cond: "Come in under weekly target 2 weeks in a row" },
  { id: "b285-under-target-month", n: 285, cat: "ALCOHOL", glyph: "flame", track: "nips", gate: "alcohol", name: "Under Target Month", cond: "Come in under weekly target 4 weeks in a row" },
  { id: "b286-under-target-quarter", n: 286, cat: "ALCOHOL", glyph: "flame", track: "nips", gate: "alcohol", name: "Under Target Quarter", cond: "Come in under weekly target 12 weeks in a row" },
  { id: "b287-half-target", n: 287, cat: "ALCOHOL", glyph: "noDrink", track: "nips", gate: "alcohol", name: "Half Target", cond: "Come in at half your weekly target" },
  { id: "b288-mindful-drinker", n: 288, cat: "ALCOHOL", glyph: "brain", track: "nips", gate: "alcohol", name: "Mindful Drinker", cond: "Log every drink for 14 days straight" },
  { id: "b289-honest-logger", n: 289, cat: "ALCOHOL", glyph: "noDrink", track: "nips", gate: "alcohol", name: "Honest Logger", cond: "Log a big night honestly without deleting" },
  { id: "b290-night-off", n: 290, cat: "ALCOHOL", glyph: "noDrink", track: "nips", gate: "alcohol", name: "Night Off", cond: "Have a drink-free night on a night you normally drink" },
  { id: "b291-social-swap", n: 291, cat: "ALCOHOL", glyph: "people", track: "nips", gate: "alcohol", name: "Social Swap", cond: "Log a social event where you had zero drinks" },
  { id: "b292-weekend-warrior", n: 292, cat: "ALCOHOL", glyph: "noDrink", track: "nips", gate: "alcohol", name: "Weekend Warrior", cond: "Have an AFD on both Saturday and Sunday in the same weekend" },
  { id: "b293-friday-night-sober", n: 293, cat: "ALCOHOL", glyph: "noDrink", track: "nips", gate: "alcohol", name: "Friday Night Sober", cond: "AFD on a Friday" },
  { id: "b294-saturday-sober", n: 294, cat: "ALCOHOL", glyph: "noDrink", track: "nips", gate: "alcohol", name: "Saturday Sober", cond: "AFD on a Saturday" },
  { id: "b295-standard-swap", n: 295, cat: "ALCOHOL", glyph: "noDrink", track: "nips", gate: "alcohol", name: "Standard Swap", cond: "Swap a full-strength drink for a mid-strength or zero" },
  { id: "b296-zero-week", n: 296, cat: "ALCOHOL", glyph: "noDrink", track: "nips", gate: "alcohol", name: "Zero Week", cond: "Zero standard drinks for a full week" },
  { id: "b297-zero-fortnight", n: 297, cat: "ALCOHOL", glyph: "noDrink", track: "nips", gate: "alcohol", name: "Zero Fortnight", cond: "Zero standard drinks for 14 days" },
  { id: "b298-mocktail-night", n: 298, cat: "ALCOHOL", glyph: "people", track: "nips", gate: "alcohol", name: "Mocktail Night", cond: "Log a non-alcoholic alternative at a social event" },
  { id: "b299-early-cut-off", n: 299, cat: "ALCOHOL", glyph: "noDrink", track: "nips", gate: "alcohol", name: "Early Cut Off", cond: "Stop drinking before 9pm 5 times" },
  { id: "b300-one-drink-night", n: 300, cat: "ALCOHOL", glyph: "noDrink", track: "nips", gate: "alcohol", name: "One Drink Night", cond: "Log only 1 standard drink on a night out" },
  { id: "b301-two-drink-cap", n: 301, cat: "ALCOHOL", glyph: "people", track: "nips", gate: "alcohol", name: "Two Drink Cap", cond: "Stay at 2 or under on a social night 5 times" },
  { id: "b302-reduced", n: 302, cat: "ALCOHOL", glyph: "noDrink", track: "nips", gate: "alcohol", name: "Reduced", cond: "Reduce weekly average by 20% over a month" },
  { id: "b303-half-last-month", n: 303, cat: "ALCOHOL", glyph: "noDrink", track: "nips", gate: "alcohol", name: "Half Last Month", cond: "Drink half as much this month vs last month" },
  { id: "b304-trend-down", n: 304, cat: "ALCOHOL", glyph: "flame", track: "nips", gate: "alcohol", name: "Trend Down", cond: "Three consecutive weeks of reducing intake" },
  { id: "b305-10-afds", n: 305, cat: "ALCOHOL", glyph: "noDrink", track: "nips", gate: "alcohol", name: "10 AFDs", cond: "10 cumulative AFDs" },
  { id: "b306-25-afds", n: 306, cat: "ALCOHOL", glyph: "noDrink", track: "nips", gate: "alcohol", name: "25 AFDs", cond: "25 cumulative AFDs" },
  { id: "b307-50-afds", n: 307, cat: "ALCOHOL", glyph: "noDrink", track: "nips", gate: "alcohol", name: "50 AFDs", cond: "50 cumulative AFDs" },
  { id: "b308-100-afds", n: 308, cat: "ALCOHOL", glyph: "noDrink", track: "nips", gate: "alcohol", name: "100 AFDs", cond: "100 cumulative AFDs" },
  { id: "b309-200-afds", n: 309, cat: "ALCOHOL", glyph: "noDrink", track: "nips", gate: "alcohol", name: "200 AFDs", cond: "200 cumulative AFDs" },
  { id: "b310-sober-socialiser", n: 310, cat: "ALCOHOL", glyph: "people", track: "nips", gate: "alcohol", name: "Sober Socialiser", cond: "Attend 5 logged social events AFD" },
  { id: "b311-role-model", n: 311, cat: "ALCOHOL", glyph: "flame", track: "nips", gate: "alcohol", name: "Role Model", cond: "Maintain under-target drinking for 6 consecutive months" },
  { id: "b312-goal-setter", n: 312, cat: "GOALS", glyph: "target", track: "goals", name: "Goal Setter", cond: "Set first goal" },
  { id: "b313-first-win", n: 313, cat: "GOALS", glyph: "target", track: "goals", name: "First Win", cond: "Complete first goal" },
  { id: "b314-three-wins", n: 314, cat: "GOALS", glyph: "target", track: "goals", name: "Three Wins", cond: "Complete 3 goals" },
  { id: "b315-five-wins", n: 315, cat: "GOALS", glyph: "target", track: "goals", name: "Five Wins", cond: "Complete 5 goals" },
  { id: "b316-ten-wins", n: 316, cat: "GOALS", glyph: "target", track: "goals", name: "Ten Wins", cond: "Complete 10 goals" },
  { id: "b317-twenty-wins", n: 317, cat: "GOALS", glyph: "target", track: "goals", name: "Twenty Wins", cond: "Complete 20 goals" },
  { id: "b318-fifty-wins", n: 318, cat: "GOALS", glyph: "target", track: "goals", name: "Fifty Wins", cond: "Complete 50 goals" },
  { id: "b319-short-game", n: 319, cat: "GOALS", glyph: "target", track: "goals", name: "Short Game", cond: "Complete a 7-day goal" },
  { id: "b320-mid-game", n: 320, cat: "GOALS", glyph: "target", track: "goals", name: "Mid Game", cond: "Complete a 30-day goal" },
  { id: "b321-long-game", n: 321, cat: "GOALS", glyph: "target", track: "goals", name: "Long Game", cond: "Complete a 90-day goal" },
  { id: "b322-epic", n: 322, cat: "GOALS", glyph: "target", track: "goals", name: "Epic", cond: "Complete a 365-day goal" },
  { id: "b323-stretch-goal", n: 323, cat: "GOALS", glyph: "target", track: "goals", name: "Stretch Goal", cond: "Complete a goal rated \"hard\"" },
  { id: "b324-consistent", n: 324, cat: "GOALS", glyph: "target", track: "goals", name: "Consistent", cond: "Complete goals in 3 consecutive months" },
  { id: "b325-goal-machine", n: 325, cat: "GOALS", glyph: "target", track: "goals", name: "Goal Machine", cond: "Complete at least one goal every month for 6 months" },
  { id: "b326-goal-champion", n: 326, cat: "GOALS", glyph: "target", track: "goals", name: "Goal Champion", cond: "Complete at least one goal every month for 12 months" },
  { id: "b327-habit-builder", n: 327, cat: "GOALS", glyph: "target", track: "goals", name: "Habit Builder", cond: "Maintain a new habit for 21 days" },
  { id: "b328-habit-locked", n: 328, cat: "GOALS", glyph: "target", track: "goals", name: "Habit Locked", cond: "Maintain a new habit for 66 days" },
  { id: "b329-habit-master", n: 329, cat: "GOALS", glyph: "target", track: "goals", name: "Habit Master", cond: "Maintain a new habit for 90 days" },
  { id: "b330-new-year-goal", n: 330, cat: "GOALS", glyph: "cake", track: "goals", name: "New Year Goal", cond: "Set a goal on January 1st" },
  { id: "b331-mid-year-review", n: 331, cat: "GOALS", glyph: "target", track: "goals", name: "Mid-Year Review", cond: "Update or complete a goal on July 1st" },
  { id: "b332-birthday-goal", n: 332, cat: "GOALS", glyph: "cake", track: "goals", name: "Birthday Goal", cond: "Set a goal on your birthday" },
  { id: "b333-family-goal", n: 333, cat: "GOALS", glyph: "target", track: "goals", name: "Family Goal", cond: "Set a goal involving a family member" },
  { id: "b334-accountability-partner", n: 334, cat: "GOALS", glyph: "target", track: "goals", name: "Accountability Partner", cond: "Share a goal with another user" },
  { id: "b335-shared-win", n: 335, cat: "GOALS", glyph: "target", track: "goals", name: "Shared Win", cond: "Complete a shared goal with another user" },
  { id: "b336-dream-big", n: 336, cat: "GOALS", glyph: "target", track: "goals", name: "Dream Big", cond: "Set a goal with a 12-month timeframe" },
  { id: "b337-quick-win", n: 337, cat: "GOALS", glyph: "target", track: "goals", name: "Quick Win", cond: "Complete a goal in under 24 hours" },
  { id: "b338-comeback-goal", n: 338, cat: "GOALS", glyph: "target", track: "goals", name: "Comeback Goal", cond: "Set a new goal within 7 days of failing one" },
  { id: "b339-never-give-up", n: 339, cat: "GOALS", glyph: "target", track: "goals", name: "Never Give Up", cond: "Restart a failed goal and complete it" },
  { id: "b340-reflection", n: 340, cat: "GOALS", glyph: "feather", track: "goals", name: "Reflection", cond: "Complete a goal review/reflection entry" },
  { id: "b341-full-circle", n: 341, cat: "GOALS", glyph: "target", track: "goals", name: "Full Circle", cond: "Complete a goal you previously failed" },
  { id: "b342-welcome", n: 342, cat: "ENGAGEMENT", glyph: "sparkle", track: "app", name: "Welcome", cond: "Complete onboarding" },
  { id: "b343-profile-complete", n: 343, cat: "ENGAGEMENT", glyph: "sparkle", track: "app", name: "Profile Complete", cond: "Fill in all profile fields" },
  { id: "b344-first-week", n: 344, cat: "ENGAGEMENT", glyph: "flame", track: "app", name: "First Week", cond: "Use the app every day for 7 days" },
  { id: "b345-first-month", n: 345, cat: "ENGAGEMENT", glyph: "flame", track: "app", name: "First Month", cond: "Use the app every day for 30 days" },
  { id: "b346-three-months", n: 346, cat: "ENGAGEMENT", glyph: "flame", track: "app", name: "Three Months", cond: "Use the app every day for 90 days" },
  { id: "b347-six-months", n: 347, cat: "ENGAGEMENT", glyph: "flame", track: "app", name: "Six Months", cond: "Use the app every day for 180 days" },
  { id: "b348-one-year", n: 348, cat: "ENGAGEMENT", glyph: "medal", track: "app", name: "One Year", cond: "Use the app every day for 365 days" },
  { id: "b349-all-sections", n: 349, cat: "ENGAGEMENT", glyph: "sparkle", track: "app", name: "All Sections", cond: "Visit every section of the app at least once" },
  { id: "b350-customiser", n: 350, cat: "ENGAGEMENT", glyph: "camera", track: "app", name: "Customiser", cond: "Update your profile photo" },
  { id: "b351-goal-decorator", n: 351, cat: "ENGAGEMENT", glyph: "target", track: "app", name: "Goal Decorator", cond: "Name and personalise a goal" },
  { id: "b352-notification-on", n: 352, cat: "ENGAGEMENT", glyph: "sparkle", track: "app", name: "Notification On", cond: "Enable push notifications" },
  { id: "b353-dark-mode", n: 353, cat: "ENGAGEMENT", glyph: "sparkle", track: "app", name: "Dark Mode", cond: "Switch to dark mode" },
  { id: "b354-settings-explorer", n: 354, cat: "ENGAGEMENT", glyph: "sparkle", track: "app", name: "Settings Explorer", cond: "Visit the settings page" },
  { id: "b355-feedback-given", n: 355, cat: "ENGAGEMENT", glyph: "ruler", track: "app", name: "Feedback Given", cond: "Submit app feedback" },
  { id: "b356-shared-the-app", n: 356, cat: "ENGAGEMENT", glyph: "sparkle", track: "app", name: "Shared the App", cond: "Share the app with someone" },
  { id: "b357-referred-a-friend", n: 357, cat: "ENGAGEMENT", glyph: "people", track: "app", name: "Referred a Friend", cond: "A friend signs up using your referral" },
  { id: "b358-five-referrals", n: 358, cat: "ENGAGEMENT", glyph: "people", track: "app", name: "Five Referrals", cond: "Five friends sign up via your referral" },
  { id: "b359-ten-referrals", n: 359, cat: "ENGAGEMENT", glyph: "people", track: "app", name: "Ten Referrals", cond: "Ten friends sign up via your referral" },
  { id: "b360-community-member", n: 360, cat: "ENGAGEMENT", glyph: "people", track: "app", name: "Community Member", cond: "Join the in-app community" },
  { id: "b361-first-comment", n: 361, cat: "ENGAGEMENT", glyph: "people", track: "app", name: "First Comment", cond: "Leave a comment or encouragement for another user" },
  { id: "b362-encourager", n: 362, cat: "ENGAGEMENT", glyph: "heart", track: "app", name: "Encourager", cond: "Leave 10 positive comments for other users" },
  { id: "b363-streak-saver", n: 363, cat: "ENGAGEMENT", glyph: "flame", track: "app", name: "Streak Saver", cond: "Resume a broken streak within 24 hours" },
  { id: "b364-comeback-kid", n: 364, cat: "ENGAGEMENT", glyph: "bolt", track: "app", name: "Comeback Kid", cond: "Return to the app after 30+ days away" },
  { id: "b365-night-check-in", n: 365, cat: "ENGAGEMENT", glyph: "sparkle", track: "app", name: "Night Check-In", cond: "Complete check-in after 10pm" },
  { id: "b366-morning-check-in", n: 366, cat: "ENGAGEMENT", glyph: "sparkle", track: "app", name: "Morning Check-In", cond: "Complete check-in before 7am" },
  { id: "b367-lunchtime-check-in", n: 367, cat: "ENGAGEMENT", glyph: "plate", track: "app", name: "Lunchtime Check-In", cond: "Complete check-in between 12-1pm" },
  { id: "b368-consistent-time", n: 368, cat: "ENGAGEMENT", glyph: "medal", track: "app", name: "Consistent Time", cond: "Check in within the same 30-minute window 7 days in a row" },
  { id: "b369-all-badges-viewed", n: 369, cat: "ENGAGEMENT", glyph: "crown", track: "app", name: "All Badges Viewed", cond: "View the full badge collection" },
  { id: "b370-badge-hunter", n: 370, cat: "ENGAGEMENT", glyph: "crown", track: "app", name: "Badge Hunter", cond: "Earn 50 badges" },
  { id: "b371-badge-collector", n: 371, cat: "ENGAGEMENT", glyph: "crown", track: "app", name: "Badge Collector", cond: "Earn 100 badges" },
  { id: "b372-badge-master", n: 372, cat: "ENGAGEMENT", glyph: "crown", track: "app", name: "Badge Master", cond: "Earn 200 badges" },
  { id: "b373-badge-legend", n: 373, cat: "ENGAGEMENT", glyph: "crown", track: "app", special: "milestone", name: "Badge Legend", cond: "Earn all available badges" },
  { id: "b374-family-first", n: 374, cat: "SOCIAL", glyph: "people", track: "social", name: "Family First", cond: "Log a family activity" },
  { id: "b375-date-night", n: 375, cat: "SOCIAL", glyph: "people", track: "social", name: "Date Night", cond: "Log a social/date night entry" },
  { id: "b376-quality-time", n: 376, cat: "SOCIAL", glyph: "people", track: "social", name: "Quality Time", cond: "Log quality time with a loved one 7 days in a row" },
  { id: "b377-social-connection", n: 377, cat: "SOCIAL", glyph: "people", track: "social", name: "Social Connection", cond: "Log a social catch-up" },
  { id: "b378-phone-call", n: 378, cat: "SOCIAL", glyph: "people", track: "social", name: "Phone Call", cond: "Log a meaningful phone call" },
  { id: "b379-acts-of-service", n: 379, cat: "SOCIAL", glyph: "people", track: "social", name: "Acts of Service", cond: "Log doing something for someone else" },
  { id: "b380-gratitude-shared", n: 380, cat: "SOCIAL", glyph: "people", track: "social", name: "Gratitude Shared", cond: "Send a gratitude message to another user" },
  { id: "b381-support-network", n: 381, cat: "SOCIAL", glyph: "people", track: "social", name: "Support Network", cond: "Add 3 contacts/accountability partners" },
  { id: "b382-community-post", n: 382, cat: "SOCIAL", glyph: "people", track: "social", name: "Community Post", cond: "Post in the community feed" },
  { id: "b383-group-goal", n: 383, cat: "SOCIAL", glyph: "target", track: "social", name: "Group Goal", cond: "Join a group challenge" },
  { id: "b384-group-win", n: 384, cat: "SOCIAL", glyph: "target", track: "social", name: "Group Win", cond: "Complete a group challenge" },
  { id: "b385-mentor", n: 385, cat: "SOCIAL", glyph: "target", track: "social", name: "Mentor", cond: "Help another user reach a goal milestone" },
  { id: "b386-inspired", n: 386, cat: "SOCIAL", glyph: "people", track: "social", name: "Inspired", cond: "Log being inspired by another user's progress" },
  { id: "b387-couples-goal", n: 387, cat: "SOCIAL", glyph: "target", track: "social", name: "Couples Goal", cond: "Complete a goal alongside a partner" },
  { id: "b388-family-challenge", n: 388, cat: "SOCIAL", glyph: "people", track: "social", name: "Family Challenge", cond: "Complete a challenge with a family member" },
  { id: "b389-new-year-new-me", n: 389, cat: "SEASONAL", glyph: "cake", track: "manual", name: "New Year New Me", cond: "Check in on January 1st" },
  { id: "b390-valentine-s-health", n: 390, cat: "SEASONAL", glyph: "cake", track: "manual", name: "Valentine's Health", cond: "Log a healthy activity on February 14th" },
  { id: "b391-st-paddy-s-sober", n: 391, cat: "SEASONAL", glyph: "cake", track: "manual", name: "St Paddy's Sober", cond: "AFD on March 17th" },
  { id: "b392-easter-active", n: 392, cat: "SEASONAL", glyph: "cake", track: "manual", name: "Easter Active", cond: "Work out over Easter long weekend" },
  { id: "b393-anzac-day", n: 393, cat: "SEASONAL", glyph: "cake", track: "manual", name: "ANZAC Day", cond: "Check in on April 25th" },
  { id: "b394-mother-s-day", n: 394, cat: "SEASONAL", glyph: "cake", track: "manual", name: "Mother's Day", cond: "Log gratitude on Mother's Day" },
  { id: "b395-winter-warrior", n: 395, cat: "SEASONAL", glyph: "snowflake", track: "manual", name: "Winter Warrior", cond: "Work out every day for the first week of winter" },
  { id: "b396-mid-year-reset", n: 396, cat: "SEASONAL", glyph: "bolt", track: "manual", name: "Mid-Year Reset", cond: "Complete a full check-in on July 1st" },
  { id: "b397-father-s-day", n: 397, cat: "SEASONAL", glyph: "cake", track: "manual", name: "Father's Day", cond: "Log a father-related activity/gratitude" },
  { id: "b398-spring-into-action", n: 398, cat: "SEASONAL", glyph: "cake", track: "manual", name: "Spring Into Action", cond: "Start a new habit on the first day of spring" },
  { id: "b399-october-challenge", n: 399, cat: "SEASONAL", glyph: "cake", track: "manual", name: "October Challenge", cond: "Complete every daily check-in in October" },
  { id: "b400-movember", n: 400, cat: "SEASONAL", glyph: "cake", track: "manual", name: "Movember", cond: "Log fitness every day in November" },
  { id: "b401-silly-season-survivor", n: 401, cat: "SEASONAL", glyph: "cake", track: "manual", name: "Silly Season Survivor", cond: "Stay under alcohol target every week in December" },
  { id: "b402-christmas-active", n: 402, cat: "SEASONAL", glyph: "cake", track: "manual", name: "Christmas Active", cond: "Work out on December 25th" },
  { id: "b403-nye-sober", n: 403, cat: "SEASONAL", glyph: "cake", track: "manual", name: "NYE Sober", cond: "AFD on December 31st" },
  { id: "b404-birthday-logged", n: 404, cat: "SEASONAL", glyph: "cake", track: "manual", name: "Birthday Logged", cond: "Log on your birthday" },
  { id: "b405-app-anniversary", n: 405, cat: "SEASONAL", glyph: "cake", track: "manual", name: "App Anniversary", cond: "Use the app on your 1-year sign-up anniversary" },
  { id: "b406-long-weekend-streak", n: 406, cat: "SEASONAL", glyph: "target", track: "manual", name: "Long Weekend Streak", cond: "Maintain all habits over a long weekend" },
  { id: "b407-holiday-mode", n: 407, cat: "SEASONAL", glyph: "cake", track: "manual", name: "Holiday Mode", cond: "Log check-ins every day of a holiday/vacation" },
  { id: "b408-back-to-routine", n: 408, cat: "SEASONAL", glyph: "cake", track: "manual", name: "Back to Routine", cond: "Complete a full check-in within 2 days of returning from holiday" },
  { id: "b409-heatwave-hydrated", n: 409, cat: "SEASONAL", glyph: "droplet", track: "manual", name: "Heatwave Hydrated", cond: "Log 3L+ water on a 35 degree+ day" },
  { id: "b410-rainy-day-workout", n: 410, cat: "SEASONAL", glyph: "snowflake", track: "manual", name: "Rainy Day Workout", cond: "Work out on a day with recorded rain" },
  { id: "b411-travel-day-protocol", n: 411, cat: "SEASONAL", glyph: "calendar", track: "manual", name: "Travel Day Protocol", cond: "Complete travel day protocol correctly" },
  { id: "b412-milestone-monday", n: 412, cat: "SEASONAL", glyph: "calendar", track: "manual", name: "Milestone Monday", cond: "Hit a personal milestone on a Monday" },
  { id: "b413-friday-feeling", n: 413, cat: "SEASONAL", glyph: "calendar", track: "manual", name: "Friday Feeling", cond: "End the week under all targets on a Friday" },
  { id: "b414-never-miss-twice", n: 414, cat: "DISCIPLINE", glyph: "shield", track: "mixed", name: "Never Miss Twice", cond: "Log after a missed day immediately" },
  { id: "b415-discipline-over-motivation", n: 415, cat: "DISCIPLINE", glyph: "shield", track: "mixed", name: "Discipline Over Motivation", cond: "Work out on a day you logged low motivation" },
  { id: "b416-showed-up", n: 416, cat: "DISCIPLINE", glyph: "dumbbell", track: "mixed", name: "Showed Up", cond: "Log a workout rated low energy but completed" },
  { id: "b417-pushed-through", n: 417, cat: "DISCIPLINE", glyph: "brain", track: "mixed", name: "Pushed Through", cond: "Complete a workout after logging stress 8/10+" },
  { id: "b418-pain-free", n: 418, cat: "DISCIPLINE", glyph: "flame", track: "mixed", name: "Pain Free", cond: "Log zero pain/injury for 30 days" },
  { id: "b419-injury-comeback", n: 419, cat: "DISCIPLINE", glyph: "snowflake", track: "mixed", name: "Injury Comeback", cond: "Return to full training after logging an injury" },
  { id: "b420-no-excuses-month", n: 420, cat: "DISCIPLINE", glyph: "shield", track: "mixed", name: "No Excuses Month", cond: "Hit every daily target for a full month" },
  { id: "b421-boring-consistency", n: 421, cat: "DISCIPLINE", glyph: "dumbbell", track: "mixed", name: "Boring Consistency", cond: "Same workout routine 4 weeks in a row" },
  { id: "b422-habit-stack", n: 422, cat: "DISCIPLINE", glyph: "target", track: "mixed", name: "Habit Stack", cond: "Complete 3 habits before 9am for 7 days" },
  { id: "b423-morning-routine", n: 423, cat: "DISCIPLINE", glyph: "medal", track: "mixed", name: "Morning Routine", cond: "Complete full morning routine 14 days in a row" },
  { id: "b424-evening-routine", n: 424, cat: "DISCIPLINE", glyph: "medal", track: "mixed", name: "Evening Routine", cond: "Complete full evening routine 14 days in a row" },
  { id: "b425-bookended-day", n: 425, cat: "DISCIPLINE", glyph: "book", track: "mixed", name: "Bookended Day", cond: "Complete both morning and evening routines in one day" },
  { id: "b426-bookended-week", n: 426, cat: "DISCIPLINE", glyph: "book", track: "mixed", name: "Bookended Week", cond: "Bookended day every day for 7 days" },
  { id: "b427-bookended-month", n: 427, cat: "DISCIPLINE", glyph: "book", track: "mixed", name: "Bookended Month", cond: "Bookended day every day for 30 days" },
  { id: "b428-zero-compromise", n: 428, cat: "DISCIPLINE", glyph: "shield", track: "mixed", name: "Zero Compromise", cond: "Hit every single target on a day you had every excuse not to" },
  { id: "b429-systems-win", n: 429, cat: "DISCIPLINE", glyph: "target", track: "mixed", name: "Systems Win", cond: "Use the app's planning tools to set up tomorrow, tonight, 7 days in a row" },
  { id: "b430-prepared", n: 430, cat: "DISCIPLINE", glyph: "plate", track: "mixed", name: "Prepared", cond: "Log the next day's meals in advance 7 times" },
  { id: "b431-environment-set", n: 431, cat: "DISCIPLINE", glyph: "plate", track: "mixed", name: "Environment Set", cond: "Log an environment engineering action" },
  { id: "b432-identity-badge", n: 432, cat: "DISCIPLINE", glyph: "feather", track: "mixed", name: "Identity Badge", cond: "Write a personal identity/values statement in profile" },
  { id: "b433-the-standard", n: 433, cat: "DISCIPLINE", glyph: "target", track: "mixed", name: "The Standard", cond: "Maintain all core habits for 90 consecutive days" },
  { id: "b434-the-dad", n: 434, cat: "FUN", glyph: "plate", track: "mixed", name: "The Dad", cond: "Log a family activity + workout + healthy meal all in one day" },
  { id: "b435-the-commuter", n: 435, cat: "FUN", glyph: "run", track: "mixed", name: "The Commuter", cond: "Log activity within 1.5km of home or work 20 times" },
  { id: "b436-office-gym", n: 436, cat: "FUN", glyph: "dumbbell", track: "mixed", name: "Office Gym", cond: "Use a workplace gym 10 times" },
  { id: "b437-pizza-and-protein", n: 437, cat: "FUN", glyph: "plate", track: "mixed", name: "Pizza and Protein", cond: "Log pizza for dinner and still hit protein target" },
  { id: "b438-the-reset", n: 438, cat: "FUN", glyph: "bolt", track: "mixed", name: "The Reset", cond: "Log a perfect day the day after your worst logged day" },
  { id: "b439-weekend-winner", n: 439, cat: "FUN", glyph: "calendar", track: "mixed", name: "Weekend Winner", cond: "Hit all targets on both Saturday and Sunday" },
  { id: "b440-long-weekend-legend", n: 440, cat: "FUN", glyph: "dumbbell", track: "mixed", name: "Long Weekend Legend", cond: "Hit all targets across a 3-day long weekend" },
  { id: "b441-public-holiday-hustle", n: 441, cat: "FUN", glyph: "cake", track: "mixed", name: "Public Holiday Hustle", cond: "Work out on a public holiday" },
  { id: "b442-one-year-older", n: 442, cat: "FUN", glyph: "feather", track: "mixed", name: "One Year Older", cond: "Log on your birthday and reflect on the past year" },
  { id: "b443-sober-driver", n: 443, cat: "FUN", glyph: "noDrink", track: "mixed", name: "Sober Driver", cond: "Log being the designated driver" },
  { id: "b444-pub-with-purpose", n: 444, cat: "FUN", glyph: "people", track: "mixed", name: "Pub With Purpose", cond: "Attend a social event and stay under 2 drinks" },
  { id: "b445-gym-selfie", n: 445, cat: "FUN", glyph: "camera", track: "mixed", name: "Gym Selfie", cond: "Upload a progress photo from the gym" },
  { id: "b446-meal-photo", n: 446, cat: "FUN", glyph: "camera", track: "mixed", name: "Meal Photo", cond: "Log a meal with a photo attached" },
  { id: "b447-the-returner", n: 447, cat: "FUN", glyph: "bolt", track: "mixed", name: "The Returner", cond: "Come back to the app after 60+ days away" },
  { id: "b448-underdog", n: 448, cat: "FUN", glyph: "target", track: "mixed", name: "Underdog", cond: "Come back from 3 failed goals in a row and complete one" },
  { id: "b449-quiet-achiever", n: 449, cat: "FUN", glyph: "target", track: "mixed", name: "Quiet Achiever", cond: "Complete 10 goals without sharing any" },
  { id: "b450-loud-and-proud", n: 450, cat: "FUN", glyph: "target", track: "mixed", name: "Loud and Proud", cond: "Share 5 goal completions with the community" },
  { id: "b451-accountability-ace", n: 451, cat: "FUN", glyph: "people", track: "mixed", name: "Accountability Ace", cond: "Check in with your accountability partner 20 times" },
  { id: "b452-the-planner", n: 452, cat: "FUN", glyph: "calendar", track: "mixed", name: "The Planner", cond: "Use the weekly planning feature every week for a month" },
  { id: "b453-sunday-set-up", n: 453, cat: "FUN", glyph: "calendar", track: "mixed", name: "Sunday Set-Up", cond: "Complete Sunday planning session 4 weeks in a row" },
  { id: "b454-the-minimalist", n: 454, cat: "FUN", glyph: "calendar", track: "mixed", name: "The Minimalist", cond: "Hit all targets with only 3 logged items in a day" },
  { id: "b455-one-percent", n: 455, cat: "FUN", glyph: "bolt", track: "mixed", name: "One Percent", cond: "Log a 1% improvement in any tracked metric" },
  { id: "b456-compound-effect", n: 456, cat: "FUN", glyph: "bolt", track: "mixed", name: "Compound Effect", cond: "Log improvements in 3 different metrics in the same week" },
  { id: "b457-the-tortoise", n: 457, cat: "FUN", glyph: "bolt", track: "mixed", name: "The Tortoise", cond: "Log consistent progress every week for 6 months with no big spikes" },
  { id: "b458-the-hare-recovered", n: 458, cat: "FUN", glyph: "dumbbell", track: "mixed", name: "The Hare Recovered", cond: "Log a massive week followed by a recovery week still on target" },
  { id: "b459-five-thirty-club", n: 459, cat: "FUN", glyph: "dumbbell", track: "mixed", name: "Five-Thirty Club", cond: "Log a workout before 5:30am" },
  { id: "b460-lunchtime-lifter", n: 460, cat: "FUN", glyph: "plate", track: "mixed", name: "Lunchtime Lifter", cond: "Work out between 12-1pm 10 times" },
  { id: "b461-the-full-package", n: 461, cat: "FUN", glyph: "droplet", track: "mixed", name: "The Full Package", cond: "Log workout + nutrition + sleep + check-in + water all in one day for 7 days" },
  { id: "b462-100-days-in", n: 462, cat: "LIFETIME", glyph: "medal", track: "mixed", name: "100 Days In", cond: "Use the app for 100 cumulative days" },
  { id: "b463-200-days-in", n: 463, cat: "LIFETIME", glyph: "medal", track: "mixed", name: "200 Days In", cond: "Use the app for 200 cumulative days" },
  { id: "b464-365-days-in", n: 464, cat: "LIFETIME", glyph: "medal", track: "mixed", name: "365 Days In", cond: "Use the app for 365 cumulative days" },
  { id: "b465-500-days-in", n: 465, cat: "LIFETIME", glyph: "medal", track: "mixed", name: "500 Days In", cond: "Use the app for 500 cumulative days" },
  { id: "b466-1000-days-in", n: 466, cat: "LIFETIME", glyph: "medal", track: "mixed", name: "1000 Days In", cond: "Use the app for 1000 cumulative days" },
  { id: "b467-10-workouts-logged", n: 467, cat: "LIFETIME", glyph: "dumbbell", track: "mixed", name: "10 Workouts Logged", cond: "Cumulative" },
  { id: "b468-50-workouts-logged", n: 468, cat: "LIFETIME", glyph: "dumbbell", track: "mixed", name: "50 Workouts Logged", cond: "Cumulative" },
  { id: "b469-100-workouts-logged", n: 469, cat: "LIFETIME", glyph: "dumbbell", track: "mixed", name: "100 Workouts Logged", cond: "Cumulative" },
  { id: "b470-250-workouts-logged", n: 470, cat: "LIFETIME", glyph: "dumbbell", track: "mixed", name: "250 Workouts Logged", cond: "Cumulative" },
  { id: "b471-500-workouts-logged", n: 471, cat: "LIFETIME", glyph: "dumbbell", track: "mixed", name: "500 Workouts Logged", cond: "Cumulative" },
  { id: "b472-1000-workouts-logged", n: 472, cat: "LIFETIME", glyph: "dumbbell", track: "mixed", name: "1000 Workouts Logged", cond: "Cumulative" },
  { id: "b473-100-meals-logged", n: 473, cat: "LIFETIME", glyph: "plate", track: "mixed", name: "100 Meals Logged", cond: "Cumulative" },
  { id: "b474-500-meals-logged", n: 474, cat: "LIFETIME", glyph: "plate", track: "mixed", name: "500 Meals Logged", cond: "Cumulative" },
  { id: "b475-1000-meals-logged", n: 475, cat: "LIFETIME", glyph: "plate", track: "mixed", name: "1000 Meals Logged", cond: "Cumulative" },
  { id: "b476-5000-meals-logged", n: 476, cat: "LIFETIME", glyph: "plate", track: "mixed", name: "5000 Meals Logged", cond: "Cumulative" },
  { id: "b477-50-check-ins", n: 477, cat: "LIFETIME", glyph: "flame", track: "mixed", name: "50 Check-Ins", cond: "Cumulative" },
  { id: "b478-100-check-ins", n: 478, cat: "LIFETIME", glyph: "flame", track: "mixed", name: "100 Check-Ins", cond: "Cumulative" },
  { id: "b479-365-check-ins", n: 479, cat: "LIFETIME", glyph: "flame", track: "mixed", name: "365 Check-Ins", cond: "Cumulative" },
  { id: "b480-500-check-ins", n: 480, cat: "LIFETIME", glyph: "flame", track: "mixed", name: "500 Check-Ins", cond: "Cumulative" },
  { id: "b481-1000-check-ins", n: 481, cat: "LIFETIME", glyph: "medal", track: "mixed", special: "milestone", name: "1000 Check-Ins", cond: "Cumulative" },
  { id: "b482-up-before-the-sun", n: 482, cat: "WILDCARD", glyph: "sun", track: "mixed", name: "Up Before the Sun", cond: "Log activity before sunrise" },
  { id: "b483-last-one-standing", n: 483, cat: "WILDCARD", glyph: "people", track: "mixed", name: "Last One Standing", cond: "Be the last active user in a group challenge" },
  { id: "b484-clean-sweep", n: 484, cat: "WILDCARD", glyph: "crown", track: "mixed", name: "Clean Sweep", cond: "Hit every single target in every category in one day" },
  { id: "b485-perfectionist", n: 485, cat: "WILDCARD", glyph: "diamond", track: "mixed", name: "Perfectionist", cond: "Hit every target to the exact number in one day" },
  { id: "b486-ghost-mode", n: 486, cat: "WILDCARD", glyph: "diamond", track: "mixed", name: "Ghost Mode", cond: "Use the app every day for a month without sharing anything" },
  { id: "b487-social-butterfly", n: 487, cat: "WILDCARD", glyph: "people", track: "mixed", name: "Social Butterfly", cond: "Share something every day for a week" },
  { id: "b488-the-philosopher", n: 488, cat: "WILDCARD", glyph: "feather", track: "mixed", name: "The Philosopher", cond: "Write a journal entry over 200 words" },
  { id: "b489-deep-thoughts", n: 489, cat: "WILDCARD", glyph: "feather", track: "mixed", name: "Deep Thoughts", cond: "Write 10 journal entries over 200 words" },
  { id: "b490-the-scientist", n: 490, cat: "WILDCARD", glyph: "plate", track: "mixed", name: "The Scientist", cond: "Log the same meal and workout for 7 days and track the result" },
  { id: "b491-pattern-finder", n: 491, cat: "WILDCARD", glyph: "flame", track: "mixed", name: "Pattern Finder", cond: "Complete 30 days of full logging" },
  { id: "b492-lucky-number", n: 492, cat: "WILDCARD", glyph: "noDrink", track: "mixed", name: "Lucky Number", cond: "Hit exactly 7 standards in a week (tracking users only)" },
  { id: "b493-round-number", n: 493, cat: "WILDCARD", glyph: "plate", track: "mixed", name: "Round Number", cond: "Hit exactly 2000 calories in a day" },
  { id: "b494-on-the-dot", n: 494, cat: "WILDCARD", glyph: "medal", track: "mixed", name: "On the Dot", cond: "Log check-in at exactly the same minute 3 days in a row" },
  { id: "b495-night-before", n: 495, cat: "WILDCARD", glyph: "calendar", track: "mixed", name: "Night Before", cond: "Prep tomorrow's plan at 11pm or later 3 times" },
  { id: "b496-first-of-the-month", n: 496, cat: "WILDCARD", glyph: "diamond", track: "mixed", name: "First of the Month", cond: "Complete a full check-in on the 1st of every month for 3 months" },
  { id: "b497-the-grinder", n: 497, cat: "WILDCARD", glyph: "cake", track: "mixed", name: "The Grinder", cond: "Log activity every single day of February" },
  { id: "b498-last-day", n: 498, cat: "WILDCARD", glyph: "cake", track: "mixed", name: "Last Day", cond: "Log on December 31st" },
  { id: "b499-legend", n: 499, cat: "WILDCARD", glyph: "dumbbell", track: "mixed", special: "ultimate", name: "Legend", cond: "Earn 300+ badges" },
  { id: "b500-the-full-package-complete", n: 500, cat: "WILDCARD", glyph: "crown", track: "mixed", special: "grandmaster", name: "The Full Package Complete", cond: "Complete every category of badge at least once" },
];

if (typeof window !== 'undefined') Object.assign(window, { BADGE_LIBRARY, BL_NEW_GLYPHS, BADGE_LIB_CATEGORIES });

export { BADGE_LIBRARY, BL_NEW_GLYPHS, BADGE_LIB_CATEGORIES };
